# Generated by Django 4.1.5 on 2025-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сообщение'),
        ),
    ]
