# Generated by Django 4.1.5 on 2025-05-01 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_request_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processed', 'В обработке'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='core_reques_status_27d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_at'], name='core_reques_created_ee7b30_idx'),
        ),
    ]
