# Generated by Django 4.1.5 on 2025-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={},
        ),
        migrations.AddField(
            model_name='productimages',
            name='public_yandex_link',
            field=models.URLField(blank=True, help_text='Вставьте публичную ссылку Яндекс.Диска, например https://disk.yandex.ru/i/...', verbose_name='Публичная ссылка (Яндекс.Диск)'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_url',
            field=models.URLField(blank=True, editable=False, verbose_name='Прямая ссылка на изображение (заполняется автоматически)'),
        ),
    ]
